name: hassfest

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  hassfest:
    name: Validate manifest.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "home-assistant/actions/hassfest@v4"
